import type {PageKit,PagePreset,WidgetSpec} from './types';
const w=(id:string,title:string,eyebrow:string,description:string,icon:string,footprint:WidgetSpec['footprint'],tone:WidgetSpec['tone']='teal',metric?:string,action?:string,status?:string):WidgetSpec=>({id,title,eyebrow,description,icon,footprint,tone,metric,action,status});
const preset=(id:string,label:string,description:string,widgets:WidgetSpec[]):PagePreset=>({id,label,description,widgets});
export const pageKits:PageKit[]=[
{id:'hub',label:'Хаб',description:'Персональная стартовая страница и следующий лучший шаг.',accent:'#2ee6c8',allowedWidgets:['featured','continue','daily','modes','insight','tournament'],presets:[
preset('focus','Focus','Один главный сценарий и короткий путь к действию',[w('featured','Ликвидность перед импульсом','FEATURED SCENARIO','Гипотеза собрана на 62%. Осталось зафиксировать инвалидацию.','◈','hero','teal','62%','Продолжить'),w('continue','Продолжить Академию','NEXT BEST ACTION','Модуль Risk & Invalidation · 7 минут','↗','wide','blue','4/8','Открыть'),w('daily','Daily Fix','3 MINUTE DRILL','Поставь инвалидацию до выбора направления.','⚡','wide','amber','+50 XP','Начать'),w('insight','План опаздывает','PERSONAL INSIGHT','В 4 из 6 решений действие появилось раньше инвалидации.','◎','full','red','76/100','Разобрать')]),
preset('bento','Bento','Сводка прогресса и несколько быстрых направлений',[w('featured','Сегодняшний сценарий','RECOMMENDED','Blind Case #014 · 4H','◈','large','teal','6 мин','Войти'),w('metric','Process Score','30 DAYS','Качество процесса','88','square','blue','76.4'),w('streak','Discipline','CURRENT STREAK','Qualified activity only','7','square','amber','7 дней'),w('rematch','Rematch готов','TRANSFER TEST','Другой актив, та же ошибка.','↻','wide','green','2 доступно','Открыть'),w('tournament','Sunday Blind #09','UPCOMING','Регистрация открыта.','◇','wide','amber','02:14:08','Подробнее')])]},
{id:'academy',label:'Академия',description:'Обучение, практика, экзамены и перенос навыка.',accent:'#5aa9ff',allowedWidgets:['path','module','lesson','exam','mastery','weak-skill'],presets:[
preset('path','Learning Path','Последовательная карта освоения',[w('path','Decision Foundations','CURRENT MODULE','Факт → гипотеза → план → инвалидация.','01','hero','blue','68%','Продолжить'),w('lesson','Evidence Only','NEXT LESSON','Что считать фактом, а что — удобным мнением.','◇','wide','teal','8 мин','Открыть'),w('practice','Guided Practice','CONTROLLED','Примени правило в историческом сценарии.','▣','wide','green','3 кейса','Начать'),w('exam','Exam 01','LOCKED GATE','Откроется после 15 Mastery Stars.','◆','full','amber','12/15','Условия')]),
preset('library','Library','Каталог модулей и персональная рекомендация',[w('weak','Invalidation Timing','RECOMMENDED','Твоя текущая зона роста.','!','large','red','61%','Учиться'),w('m1','Price Structure','MODULE 02','Структура, режим и зоны.','02','square','blue','72%'),w('m2','Risk & Invalidation','MODULE 05','Сначала риск, потом желание.','05','square','amber','44%'),w('m3','Discipline','MODULE 08','Протокол под давлением.','08','wide','teal','81%','Открыть')])]},
{id:'arena',label:'Арена',description:'Режимы практики и исторические сценарии.',accent:'#2ee6c8',allowedWidgets:['quick','blind','conflict','rematch','post-loss','filters'],presets:[
preset('modes','Mode Board','Выбор режима по текущей задаче',[w('quick','Quick Arena Run','8 MINUTES','Смешанный сценарий и случайный loadout.','▶','large','teal','1 Energy','Играть'),w('blind','Blind Scenario','12 MINUTES','Без имени актива, даты и чужих мнений.','◉','square','blue','1 Energy'),w('conflict','Conflict Scenario','10 MINUTES','Источники противоречат друг другу.','⇄','square','amber','1 Energy'),w('rematch','Rematch','TRANSFER','Новый контекст, та же угроза.','↻','wide','green','2 готовы','Открыть'),w('post','Post-Loss Protocol','RECOVERY','Верни дисциплину до следующего решения.','＋','wide','red','6 мин','Начать')]),
preset('featured','Featured Run','Один рекомендуемый режим и дополнительные варианты',[w('blind','Blind Scenario #014','FEATURED RUN','Будущее скрыто. Решение оценивается до исхода.','◉','hero','teal','12 мин','Начать'),w('quick','Quick Run','FAST','Минимально достаточный анализ.','▶','wide','blue','8 мин','Играть'),w('rematch','Rematch','READY','Проверь перенос навыка.','↻','wide','green','2 кейса','Открыть')])]},
{id:'tournaments',label:'Турниры',description:'Регистрация, live-события, сезоны и результаты.',accent:'#f0a64d',allowedWidgets:['hero','registration','qualification','countdown','leaderboard','season','history'],presets:[
preset('upcoming','Upcoming','Подготовка и регистрация',[w('hero','Sunday Blind Archive #09','WEEKLY TOURNAMENT','Один срез, одинаковые данные и server scoring.','♜','hero','amber','02:14:08','Зарегистрироваться'),w('qual','Квалификация','REQUIREMENTS','Onboarding, 3 solo runs, 15 Mastery Stars.','✓','wide','blue','12/15','Продолжить'),w('rules','Правила','FAIR PLAY','Speed — только объявленный tie-breaker.','§','wide','teal','Score v1','Читать'),w('my','Мои турниры','HISTORY','Результаты и зарегистрированные события.','◫','full','green','3 события','Открыть')]),
preset('live','Live','Текущий турнир и leaderboard',[w('live','Arena Season · Live','LIVE NOW','Одинаковый ScenarioPackage для всех участников.','●','large','red','18:42','Продолжить'),w('rank','Текущий ранг','LEADERBOARD','Твой score принят сервером.','27','square','amber','#27'),w('quality','Quality Score','CURRENT RUN','Process first.','88','square','teal','88/100'),w('board','Leaderboard Preview','TOP 3','Публичные профили и cosmetics без преимущества.','≡','full','blue','1 284','Открыть')])]},
{id:'shop',label:'Магазин',description:'Coins, cosmetics, Premium и поддержка проекта.',accent:'#50c890',allowedWidgets:['featured','coin-pack','cosmetic','premium','pass','founder','receipt'],presets:[
preset('featured','Featured','Каталог без pay-to-win',[w('premium','Premium · 30 дней','FEATURED','Расширенная аналитика, история и profile theme.','✦','hero','green','599 Coins','Подробнее'),w('coins','Coin Packs','BALANCE','Telegram Stars используются только в checkout.','◉','wide','teal','320 Coins','Пополнить'),w('cosmetic','Decision Seal Skin','COSMETIC','Меняет оформление, но не score.','◇','wide','blue','400 Coins','Смотреть'),w('founder','Founder Support','LIMITED','Поддержка инфраструктуры без инвестиционных обещаний.','◆','full','amber','299 Coins','Состав')]),
preset('catalog','Catalog','Компактная витрина категорий',[w('c1','Profile Frames','COSMETICS','Публичное оформление профиля.','▣','square','blue','от 120'),w('c2','Card Skins','COSMETICS','Только визуальное оформление.','▤','square','teal','от 400'),w('pass','Arena Pass','30 DAYS','Турнирные входы и seasonal track.','♜','large','amber','749 Coins','Подробнее'),w('energy','Energy Services','CONVENIENCE','Не меняет Quality Score.','⚡','wide','green','от 20','Открыть')])]}];
export const getKit=(id:string):PageKit=>{const found=pageKits.find(k=>k.id===id);return found??(pageKits[0]as PageKit)};